### ISSUE TITLE
error occurred while loading psacalc2.ado

### ISSUE THREAD

**Issue by paulpelzl** [ArthurHowardMorris/psacalc_supports_reghdfe#1] opened 2021-11-10 12:12 UTC
Hi Arthur,

 Unfortunately I get an error message when I run psacalc2 after a reghdfe estimation. This holds both for my data and for your example data. The error message looks like this:

< is not a valid command name
(error occurred while loading psacalc2.ado)

 I have attached a STATA log file with your example data to illustrate the issue further.

Hope you can help!

Thanks,
Paul
[psacalc arthur's example.log](https://github.com/ArthurHowardMorris/psacalc_supports_reghdfe/files/7512551/psacalc.arthur.s.example.log)

**Comment by ArthurHowardMorris** [comment] 2021-11-11 01:56
First let's confirm that `psacalc2` is in the correct location:

`which psacalc2`

should return a path that is in the list returned by:

`adopath`

If not you'll get `r(199)`.

**Comment by ArthurHowardMorris** [comment] 2021-11-11 02:11
The message `error occurred while loading` and error 199 usually indicates that  something within `psacalc2.ado` has been corrupted. You can see a similar example in this [Statalist post](https://www.stata.com/statalist/archive/2012-02/msg00975.html)

You can verify this by comparing the file on your computer to the [file on git hub](https://github.com/ArthurHowardMorris/psacalc_supports_reghdfe/blob/main/psacalc2.ado).

Use `viewsource psacalc2.ado` to view the local version of the file as Stata sees it.

**Comment by ArthurHowardMorris** [comment] 2021-11-15 02:14
I'm closing this issue since Paul confirmed to me off-line that the problem was a corrupted file.

**Comment by ArthurHowardMorris** [comment] 2021-11-15 02:14
I'm closing this issue since Paul confirmed to me off-line that the problem was a corrupted file.

**Closed as completed by ArthurHowardMorris** 2021-11-15 02:14 UTC
Labels: good first issue, installation problem
